=== Paolo-Maffei/freebus-fts/freebus-fts-tools/ft12-sim/src/main/java/org/freebus/ft12sim/FT12sim.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema targetNamespace="http://www.freebus.org/FT12sim" elementFormDefault="qualified" xmlns="http://www.w3.org/2001/XMLSchema" xmlns:FT12sim="http://www.freebus.org/FT12sim">

    <element name="sequences" type="FT12sim:sequences"></element>
    
    <complexType name="sequences">
    	<sequence maxOccurs="unbounded" minOccurs="1">
    		<element name="sequence" type="FT12sim:sequence"></element>
    	</sequence>
    </complexType>
    
    <complexType name="sequence">
    	<sequence>
            <element name="Discription" type="string" maxOccurs="1" minOccurs="1"></element>
            <element name="resieve" type="FT12sim:frame" maxOccurs="1" minOccurs="1"></element>
    		<element name="transmitframes" type="FT12sim:transmitframes"
    			maxOccurs="1" minOccurs="1">
    		</element>
    	</sequence>
    </complexType>


    <complexType name="frame">
    	<sequence>
    		<element name="Telegram" type="FT12sim:Telegram"></element>
    	</sequence>
    </complexType>

    <complexType name="transmitframes">
    	<sequence>
    		<element name="frame" type="FT12sim:frame" maxOccurs="unbounded" minOccurs="1"></element>
    	</sequence>
    </complexType>


    <simpleType name="Telegram">
    	<restriction base="string">
    		<pattern value="[A-F 0-9]+"></pattern>
    	</restriction>
    </simpleType>
</schema>

=== Paolo-Maffei/freebus-fts/freebus-fts-tools/ft12-sim/src/main/java/org/freebus/ft12sim/FT12sim.xml
<?xml version="1.0" encoding="UTF-8"?>
<FT12sim:sequences xmlns:FT12sim="http://www.freebus.org/FT12sim" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.freebus.org/FT12sim FT12sim.xsd ">
  <FT12sim:sequence>
    <FT12sim:Discription>FT12sim:Discription</FT12sim:Discription>
    <FT12sim:resieve>
      <FT12sim:Telegram>AD</FT12sim:Telegram>
    </FT12sim:resieve>
    <FT12sim:transmitframes>
      <FT12sim:frame>
        <FT12sim:Telegram>AC</FT12sim:Telegram>
      </FT12sim:frame>
    </FT12sim:transmitframes>
  </FT12sim:sequence>
  <FT12sim:sequence>
  	<FT12sim:Discription>FT12sim:Discription</FT12sim:Discription>
  	<FT12sim:resieve>
  		<FT12sim:Telegram>AA</FT12sim:Telegram>
  	</FT12sim:resieve>
  	<FT12sim:transmitframes>
  		<FT12sim:frame>
  			<FT12sim:Telegram>A</FT12sim:Telegram>
  		</FT12sim:frame>
  		<FT12sim:frame>
  			<FT12sim:Telegram>A</FT12sim:Telegram>
  		</FT12sim:frame>
  		<FT12sim:frame>
  			<FT12sim:Telegram>A</FT12sim:Telegram>
  		</FT12sim:frame>
  		<FT12sim:frame>
  			<FT12sim:Telegram>A</FT12sim:Telegram>
  		</FT12sim:frame>
  	</FT12sim:transmitframes>
  </FT12sim:sequence>
</FT12sim:sequences>

=== Paolo-Maffei/freebus-fts/freebus-fts-tools/ft12-sim/FT12sim.xml
<?xml version="1.0" encoding="UTF-8"?>
<FT12sim:sequences xmlns:FT12sim="http://www.freebus.org/FT12sim"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.freebus.org/FT12sim FT12sim.xsd ">
	<FT12sim:sequence>
		<FT12sim:Discription>test</FT12sim:Discription>
		<FT12sim:resieve>
			<FT12sim:Telegram>68 02 02 68 53 A7 FA 16</FT12sim:Telegram>
		</FT12sim:resieve>
		<FT12sim:transmitframes>
			<FT12sim:Telegram>68 0A 0A 68 F3 A8 11 01 00 05 67 00 00 00 19 16</FT12sim:Telegram>

		</FT12sim:transmitframes>
	</FT12sim:sequence>
	<FT12sim:sequence>
		<FT12sim:Discription>test</FT12sim:Discription>
		<FT12sim:resieve>
			<FT12sim:Telegram>68 02 02 68 73 A7 1A 16</FT12sim:Telegram>
		</FT12sim:resieve>
		<FT12sim:transmitframes>
			<FT12sim:Telegram>68 0A 0A 68 D3 A8 11 01 00 05 67 00 00 00 F9 16</FT12sim:Telegram>

		</FT12sim:transmitframes>
	</FT12sim:sequence>




</FT12sim:sequences>
